# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dailyWorkouts' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dailyWorkouts
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  target 'dailyWorkouts-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dailyWorkoutsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'dailyWorkouts-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dailyWorkouts-tvOS

end
